//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuBolaoFavoritoService.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIDIOMA
    {
        public TIDIOMA()
        {
            this.TDICIONARIO = new HashSet<TDICIONARIO>();
        }
    
        public System.Guid IDENTIFICADOR { get; set; }
        public string COD_IDIOMA { get; set; }
    
        public virtual ICollection<TDICIONARIO> TDICIONARIO { get; set; }
    }
}
