//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuBolaoFavoritoService.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPONTUACAO
    {
        public TPONTUACAO()
        {
            this.TPALPITE = new HashSet<TPALPITE>();
        }
    
        public System.Guid IDENTIFICADOR { get; set; }
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public short VALOR { get; set; }
        public short PRIORIDADE { get; set; }
    
        public virtual ICollection<TPALPITE> TPALPITE { get; set; }
    }
}
