//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuBolaoFavoritoService.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRECURSO
    {
        public TRECURSO()
        {
            this.TPACOTE_TRECURSO = new HashSet<TPACOTE_TRECURSO>();
            this.TPALPITE = new HashSet<TPALPITE>();
            this.TUSUARIO_RECURSO = new HashSet<TUSUARIO_RECURSO>();
        }
    
        public System.Guid IDENTIFICADOR { get; set; }
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public short PESO { get; set; }
    
        public virtual ICollection<TPACOTE_TRECURSO> TPACOTE_TRECURSO { get; set; }
        public virtual ICollection<TPALPITE> TPALPITE { get; set; }
        public virtual ICollection<TUSUARIO_RECURSO> TUSUARIO_RECURSO { get; set; }
    }
}
