//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuBolaoFavoritoService.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRODADA
    {
        public TRODADA()
        {
            this.TJOGO = new HashSet<TJOGO>();
        }
    
        public System.Guid IDENTIFICADOR { get; set; }
        public string NOME { get; set; }
        public short NUMERO { get; set; }
        public short PESO { get; set; }
        public System.Guid ID_COMPETICAO { get; set; }
    
        public virtual TCOMPETICAO TCOMPETICAO { get; set; }
        public virtual ICollection<TJOGO> TJOGO { get; set; }
    }
}
