//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuBolaoFavoritoService.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTIME
    {
        public TTIME()
        {
            this.TJOGO1 = new HashSet<TJOGO>();
            this.TJOGO2 = new HashSet<TJOGO>();
            this.TUSUARIO_TIME = new HashSet<TUSUARIO_TIME>();
        }
    
        public System.Guid IDENTIFICADOR { get; set; }
        public string NOME_CURTO { get; set; }
        public string NOME_LONGO { get; set; }
        public Nullable<System.Guid> ID_ARQUIVO { get; set; }
    
        public virtual TARQUIVO TARQUIVO { get; set; }
        public virtual ICollection<TJOGO> TJOGO1 { get; set; }
        public virtual ICollection<TJOGO> TJOGO2 { get; set; }
        public virtual ICollection<TUSUARIO_TIME> TUSUARIO_TIME { get; set; }
    }
}
