//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuBolaoFavoritoService.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSUARIO_TIME
    {
        public System.Guid IDENTIFICADOR { get; set; }
        public System.Guid ID_USUARIO { get; set; }
        public System.Guid ID_TIME { get; set; }
    
        public virtual TTIME TTIME { get; set; }
        public virtual TUSUARIO TUSUARIO { get; set; }
    }
}
