//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuBolaoFavoritoService.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSUARIO_RECURSO
    {
        public System.Guid IDENTIFICADOR { get; set; }
        public System.Guid ID_RECURSO { get; set; }
        public short QUANTIDADE { get; set; }
    
        public virtual TRECURSO TRECURSO { get; set; }
    }
}
